#!/usr/bin/env python3
"""Connect the final five fragmented physiology graphs for issue #183."""

from __future__ import annotations
import argparse
import sys
import tempfile
from pathlib import Path
from typing import Any
import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path[:0] = [str(ROOT / "scripts"), str(ROOT / "src")]
from connect_morphology_graphs_183 import _components, _edge_key  # noqa: E402
from traitmech.curate.curation_event import record_curation_event  # noqa: E402
from traitmech.validation.write_validated import write_validated_trait  # noqa: E402

TIMESTAMP = "2026-08-31T11:45:00Z"
ACTION = "CONNECT_CAUSAL_GRAPH_COMPONENTS"
EXPECTED_COMPONENTS = {
    "physiology/chemolithoheterotrophic": 3,
    "physiology/chemolithotrophic": 5,
    "physiology/chemoorganotrophic": 3,
    "physiology/lithoautotrophic": 3,
    "physiology/lithoheterotrophic": 2,
}


def ev(doi: str, snippet: str, notes: str) -> list[dict[str, str]]:
    return [{"reference": f"DOI:{doi}", "snippet": snippet, "notes": notes}]


ADDITIONS: dict[str, list[dict[str, Any]]] = {
    "physiology/chemolithoheterotrophic": [
        {
            "subject": "thiosulfate",
            "predicate": "example of",
            "object": "reduced_sulfur_compound",
            "description": "Thiosulfate is a reduced sulfur electron donor oxidized during chemolithomixotrophic growth.",
            "evidence": ev(
                "10.1111/1462-2920.13232",
                "obligate aerobic chemolithomixotroph that can oxidize sulfide, thiosulfate and elemental sulfur",
                "Verified against the open primary article.",
            ),
            "predicate_id": "rdfs:subClassOf",
        },
        {
            "subject": "branched_thiosulfate_oxidation",
            "predicate": "contributes to",
            "object": "respiratory_chain",
            "description": "Branched thiosulfate oxidation transfers substrate electrons into respiratory cytochromes.",
            "evidence": ev(
                "10.1128/AEM.00956-13",
                "oxidizes sulfone, as well as sulfane, sulfur atoms to sulfate by transferring electrons to c-type cytochromes",
                "Verified against the open primary article.",
            ),
            "predicate_id": "RO:0002326",
        },
    ],
    "physiology/chemolithotrophic": [
        {
            "subject": "ammonia",
            "predicate": "example of",
            "object": "inorganic_chemical_donor",
            "description": "Ammonia is the energy-yielding inorganic substrate for chemolithotrophic ammonia oxidizers.",
            "evidence": ev(
                "10.1128/AEM.01038-21",
                "ammonium, which AOA and AOB utilize as their sole source of energy and nitrogen",
                "Verified against the open primary competition study.",
            ),
            "predicate_id": "rdfs:subClassOf",
        },
        {
            "subject": "ammonia",
            "predicate": "contributes to",
            "object": "nitrification_rate",
            "description": "The ammonia-to-nitrite step contributes to the measured nitrification rate.",
            "evidence": ev(
                "10.1128/AEM.01038-21",
                "first step, ammonia oxidation to nitrite",
                "Verified against the open primary competition study.",
            ),
            "predicate_id": "RO:0002326",
        },
        {
            "subject": "thiosulfate",
            "predicate": "example of",
            "object": "inorganic_chemical_donor",
            "description": "Thiosulfate can serve as the sole inorganic electron source for chemolithotrophic growth.",
            "evidence": ev(
                "10.1111/j.1574-6968.1991.tb04611.x",
                "with crystalline elemental sulfur (S°) and thiosulfate as sole electron source",
                "Verified against the public primary-study abstract.",
            ),
            "predicate_id": "rdfs:subClassOf",
        },
        {
            "subject": "atp",
            "predicate": "participates in",
            "object": "calvin_benson_bassham_cycle",
            "description": "ATP generated by lithotrophic energy metabolism supplies the CBB carbon-fixation cycle.",
            "evidence": ev(
                "10.1128/aem.00748-24",
                "To fuel CO2 fixation by the Calvin-Benson-Bassham (CBB) cycle, C. necator generates ATP",
                "Verified against the open primary article.",
            ),
            "predicate_id": "biolink:participates_in",
        },
    ],
    "physiology/chemoorganotrophic": [
        {
            "subject": "aerobic_respiration",
            "predicate": "contributes to",
            "object": "respiratory_chain",
            "description": "Oxygen-dependent respiration is a terminal-acceptor mode of the respiratory chain.",
            "evidence": ev(
                "10.1099/00221287-98-1-231",
                "both oxygen and nitrate (or nitrite or chlorate) levels were continuously monitored during bacterial respiration",
                "Verified against the public primary-study abstract.",
            ),
            "predicate_id": "RO:0002326",
        },
        {
            "subject": "anaerobic_respiration",
            "predicate": "contributes to",
            "object": "respiratory_chain",
            "description": "Nitrate reduction provides an anaerobic terminal-acceptor mode of the respiratory chain.",
            "evidence": ev(
                "10.1099/00221287-98-1-231",
                "commenced nitrate reduction when all the oxygen had been consumed",
                "Verified against the public primary-study abstract.",
            ),
            "predicate_id": "RO:0002326",
        },
    ],
    "physiology/lithoautotrophic": [
        {
            "subject": "membrane_dehydrogenase",
            "predicate": "contributes to",
            "object": "respiratory_energy_conservation",
            "description": "Membrane dehydrogenases reduce quinone and drive an electron-transport chain that builds proton motive force.",
            "evidence": ev(
                "10.1128/aem.00748-24",
                "Membrane-bound (de-)hydrogenases couple the oxidation reaction to the reduction of a universal quinone",
                "Verified against the open primary article.",
            ),
            "predicate_id": "RO:0002326",
        },
        {
            "subject": "nadh_reducing_equivalents",
            "predicate": "example of",
            "object": "reducing_power",
            "description": "NADH generated by reverse electron flow is reducing power for lithoautotrophic carbon fixation.",
            "evidence": ev(
                "10.1038/s41396-021-01015-8",
                "NADH dehydrogenase can also dissipate the PMF to couple electrons from the ubiquinone pool to NAD+ reduction using a process called reverse electron flow",
                "Verified against the open primary article.",
            ),
            "predicate_id": "rdfs:subClassOf",
        },
    ],
    "physiology/lithoheterotrophic": [],
}
REMOVALS = {
    "physiology/lithoheterotrophic": {
        "nodes": {"conductive_pili_cytochromes", "diet"},
        "edges": {("conductive_pili_cytochromes", "enables", "diet")},
    }
}


def transform(slug: str, doc: dict[str, Any]) -> bool:
    graphs = doc.get("causal_graphs") or []
    if len(graphs) != 1 or graphs[0].get("scope_status") != "MECHANISTIC":
        raise ValueError(f"{slug}: expected one MECHANISTIC graph")
    graph = graphs[0]
    additions = ADDITIONS[slug]
    before = _components(graph)
    expected = {_edge_key(e): e for e in additions}
    existing = {_edge_key(e): e for e in graph.get("edges") or []}
    removal = REMOVALS.get(slug, {"nodes": set(), "edges": set()})
    remove_nodes = removal["nodes"]
    remove_edges = removal["edges"]
    present = set(existing) & set(expected)
    nodes = {n["node_id"] for n in graph.get("nodes") or []}
    removal_present = bool(nodes & remove_nodes)
    if before == 1:
        if present != set(expected) or removal_present:
            raise ValueError(f"{slug}: connected graph does not match exact migration state")
        if any(existing[k] != e for k, e in expected.items()):
            raise ValueError(f"{slug}: connector drifted after migration")
        return False
    if present:
        raise ValueError(f"{slug}: partial connector replay: {sorted(present)}")
    if before != EXPECTED_COMPONENTS[slug]:
        raise ValueError(f"{slug}: expected {EXPECTED_COMPONENTS[slug]} components, found {before}")
    if remove_nodes and nodes & remove_nodes != remove_nodes:
        raise ValueError(f"{slug}: removal state drifted")
    graph["edges"] = [e for e in graph.get("edges") or [] if _edge_key(e) not in remove_edges]
    graph["nodes"] = [n for n in graph.get("nodes") or [] if n["node_id"] not in remove_nodes]
    nodes = {n["node_id"] for n in graph["nodes"]}
    for edge in additions:
        if edge["subject"] not in nodes or edge["object"] not in nodes:
            raise ValueError(f"{slug}: connector endpoint missing")
        if not edge.get("evidence") or any(
            not x.get("reference") or not x.get("snippet") for x in edge["evidence"]
        ):
            raise ValueError(f"{slug}: connector lacks evidence")
        graph.setdefault("edges", []).append(edge)
    if _components(graph) != 1:
        raise ValueError(f"{slug}: repair did not reach one component")
    detail = (
        f"added {len(additions)} public-source connector(s)"
        if additions
        else "removed the disconnected, out-of-scope DIET island"
    )
    record_curation_event(
        doc,
        curator="codex",
        action=ACTION,
        changes=f"Resolved issue #183 graph fragmentation ({before} components to 1): {detail}. No paid research service was called.",
        llm_assisted=True,
        timestamp=TIMESTAMP,
        upsert=True,
    )
    return True


def apply(write: bool = False) -> int:
    changed = 0
    for slug in sorted(ADDITIONS):
        path = ROOT / "data" / "traits" / f"{slug}.yaml"
        doc = yaml.safe_load(path.read_text()) or {}
        if not transform(slug, doc):
            continue
        changed += 1
        if write:
            write_validated_trait(doc, path)
        else:
            with tempfile.TemporaryDirectory() as tmp:
                write_validated_trait(doc, Path(tmp) / path.name)
    print(f"{'applied' if write else 'dry run'}: repaired {changed} graph(s)")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    raise SystemExit(apply(parser.parse_args().apply))
