#!/usr/bin/env python3
"""Burn down the INCONSISTENT_NODE_TYPE families the SCHEMA already settles (#356).

#366 detected the class and baselined it: 294 occurrences across 63 node_ids
carrying more than one ``node_type``. This is the first burn-down tranche, and
it is deliberately the one that needs no new judgement — because
``CausalNodeTypeEnum`` in src/traitmech/schema/traitmech.yaml names three of
these very nodes as its canonical examples:

    STATE     "A bioenergetic or molecular state of the cell (e.g. PROTON
               MOTIVE FORCE, redox state of the quinone pool) ... Distinct from
               a process: the state is the gradient / steady-value, not its
               establishment."
    QUALITY   "A quality or measurable attribute of a cellular component
               (e.g. MEMBRANE FLUIDITY, GC content, motility speed)"
    CAPACITY  "A metabolic or functional capacity — an electron-donating pool,
               ATP charge, or other reservoir-of-X notion ... Examples include
               REDUCING POWER (NADH/NADPH pool)"

So the corpus disagreed with its own schema, in the schema's own examples. That
is the cheapest possible tranche to be right about, which is why it goes first.

EVERY DESCRIPTION WAS READ BEFORE RETYPING, because #352's lesson is that a
retype can mask a rename: a node whose description means something else needs a
different node_id, not a different type. Two of the five families turned on
exactly that reading — see membrane_fluidity below.

Usage:
    python scripts/migrate_node_type_consistency.py [--dry-run]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from traitmech.curate.curation_event import record_curation_event  # noqa: E402
from traitmech.validation.write_validated import emit_trait_yaml  # noqa: E402

TRAITS = REPO_ROOT / "data" / "traits"

# Fixed, not wall-clock: pages/ derives "Corpus as of" from the latest
# curation_history entry (#228).
TIMESTAMP = "2026-08-15T02:00:00Z"
ACTION = "NORMALISE_NODE_TYPE"

# node_id -> (target type, why). Applied to EVERY occurrence that disagrees.
RETYPE: dict[str, tuple[str, str]] = {
    "proton_motive_force": (
        "STATE",
        "The schema's OWN example of STATE: 'a bioenergetic or molecular state of the "
        "cell (e.g. proton motive force ...) ... the state is the gradient / "
        "steady-value, not its establishment'. All 35 occurrences describe the "
        "gradient -- every description across all four types reads 'electrochemical "
        "proton gradient', including the 13 typed BIOLOGICAL_PROCESS ('Transmembrane "
        "electrochemical gradient generated by respiration'), which name the gradient "
        "and its provenance rather than the generating process. Nothing here means "
        "the establishment, so this is a retype and not a rename; records that DO "
        "mean the process already use a separate id (proton_motive_force_generation "
        "in ph_delta.yaml). Also settles the one edge #356 was filed for: "
        "phototrophic.yaml's CAPACITY typing was blocking `powers` (METPO:2007900), "
        "which is gated to BIOLOGICAL_PROCESS|STATE.",
    ),
    "membrane_fluidity": (
        "QUALITY",
        "The schema's OWN example of QUALITY: 'a quality or measurable attribute of a "
        "cellular component (e.g. membrane fluidity ...)'. 24 of 25 occurrences are "
        "already QUALITY and describe 'the physical state of the lipid bilayer'. The "
        "lone BIOLOGICAL_PROCESS one (temperature_delta_mid2.yaml) is the interesting "
        "case: its DESCRIPTION said 'Maintenance of optimal membrane fluidity', which "
        "is a process and would argue for a rename rather than a retype -- but its "
        "EDGES read the other way, 'unsaturated_fatty_acids -increases-> "
        "membrane_fluidity -enables-> broad_thermal_adaptation', which is the "
        "homeoviscous-adaptation cascade acting on the PROPERTY, and matches how the "
        "other 24 are wired. Three signals (schema, 24 peers, its own edges) against "
        "one (its description), so the description is what was wrong; it is corrected "
        "here rather than the node being renamed.",
    ),
    "membrane_fluidity_homeostasis": (
        "BIOLOGICAL_PROCESS",
        "The counterpart of the above, and the reason the rename was not needed: this "
        "id already exists for the process sense. Both occurrences describe "
        "'Maintenance of membrane fluidity ...', and the schema's STATE definition "
        "excludes exactly this -- 'the state is the gradient / steady-value, NOT ITS "
        "ESTABLISHMENT'. Maintenance is establishment. So the STATE-typed one "
        "(temperature_delta_high.yaml) is retyped to match the process it describes.",
    ),
    "reducing_power": (
        "CAPACITY",
        "The schema's OWN example of CAPACITY: 'an electron-donating pool, ATP charge, "
        "or other reservoir-of-X notion ... Examples include reducing power "
        "(NADH/NADPH pool)'. The lone CHEMICAL occurrence "
        "(metabolism/photosynthesis.yaml) describes 'NADPH/NAD(P)H reducing "
        "equivalents', i.e. the pool, not a single species -- which is the very "
        "distinction CAPACITY exists to draw, and the one docs/CURATION_PLAYBOOK.md "
        "records as the reservoir sense that must NOT be retyped to TRAIT (#352).",
    ),
    "cytoplasmic_buffering_capacity": (
        "CAPACITY",
        "A reservoir, not a process: the playbook's CAPACITY table names this node "
        "explicitly as the reservoir sense ('Capacity of cytoplasmic buffers to absorb "
        "pH fluctuations'). The lone BIOLOGICAL_PROCESS occurrence "
        "(ph_optimum_mid2.yaml) describes 'Buffering of the cytoplasm (e.g. phosphate "
        "pools) absorbing pH fluctuations' -- the same pool the other three call a "
        "capacity.",
    ),
}

# Descriptions corrected where the retype rests on the description being wrong.
REDESCRIBE: dict[tuple[str, str], tuple[str, str]] = {
    ("environment/temperature_delta_mid2.yaml", "membrane_fluidity"): (
        "Physical state of the lipid bilayer that must be maintained across "
        "temperatures for transport and growth.",
        "Was 'Maintenance of optimal membrane fluidity across temperatures', which "
        "describes the homeostatic process rather than the node its edges use. "
        "Aligned with the 24 peer occurrences so the id means one thing.",
    ),
}


def apply(dry_run: bool = False) -> int:
    changed_files: dict[str, list[str]] = {}
    for path in sorted(TRAITS.rglob("*.yaml")):
        try:
            doc = yaml.safe_load(path.read_text())
        except yaml.YAMLError:
            continue
        if not isinstance(doc, dict):
            continue
        rel = str(path.relative_to(TRAITS))
        notes: list[str] = []
        for graph in (doc.get("causal_graphs") or []):
            for node in (graph.get("nodes") or []):
                nid = node.get("node_id")
                if nid not in RETYPE:
                    continue
                target, _why = RETYPE[nid]
                if node.get("node_type") != target:
                    was = node.get("node_type")
                    node["node_type"] = target
                    notes.append(f"{nid}: {was} -> {target}")
                    print(f"  retype  {rel:52s} {nid} {was} -> {target}")
                key = (rel, nid)
                if key in REDESCRIBE:
                    new_desc, _why2 = REDESCRIBE[key]
                    if node.get("description") != new_desc:
                        node["description"] = new_desc
                        notes.append(f"{nid}: description aligned with its 24 peers")
                        print(f"  redescribe {rel:49s} {nid}")
        if notes:
            # One rationale per node touched, in first-seen order and deduped:
            # a file may touch two families, and the audit trail should carry the
            # reasoning for each rather than a bare list of type changes.
            touched = list(dict.fromkeys(n.split(":")[0] for n in notes))
            rationale = " ".join(RETYPE[n][1] for n in touched if n in RETYPE)
            record_curation_event(
                doc, curator="claude", action=ACTION, llm_assisted=True,
                timestamp=TIMESTAMP,
                changes=("Normalised causal-node type(s) so one node_id means one thing "
                         f"corpus-wide (issue 356): {'; '.join(notes)}. {rationale}"),
            )
            changed_files[rel] = notes
            if not dry_run:
                path.write_text(emit_trait_yaml(doc))
    print(f"\n{sum(len(v) for v in changed_files.values())} change(s) across "
          f"{len(changed_files)} file(s){' (dry run)' if dry_run else ''}", file=sys.stderr)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    return apply(ap.parse_args().dry_run)


if __name__ == "__main__":
    sys.exit(main())
