window.searchData = [
 {
  "discussion_id": "kgscan-30bcdf4a32b0",
  "prompt": "This record routes two independent paths to immune evasion -- complement-regulator binding by surface proteins, and effector delivery through the T3SS. In a given host, is either route sufficient on its own, or does established infection require both?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "animal pathogen",
  "source_id": "METPO:1004002",
  "source_file": "animal_pathogen.yaml",
  "attaches_to": [
   "causal_graphs#immune_evasion"
  ],
  "rationale": "The graph draws both arrows into the same node without saying whether they are alternatives or partners. If either is sufficient, single-target antivirulence strategies are viable; if evasion needs both, only combination approaches will work, and the two edges should carry that dependency rather than reading as parallel routes.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/animal_pathogen.html#kgscan-30bcdf4a32b0"
 },
 {
  "discussion_id": "kgscan-aa46cc9b34ab",
  "prompt": "This record draws nitric oxide straight to biofilm dispersal with nothing in between, while c-di-GMP sits in the same graph wired only to the sessile state. Is the NO effect on dispersal mediated by lowering c-di-GMP, and should that intermediate be on the edge?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "biofilm formation",
  "source_id": "traitmech:000053",
  "source_file": "biofilm_formation.yaml",
  "attaches_to": [
   "causal_graphs#biofilm_dispersal",
   "causal_graphs#nitric_oxide",
   "causal_graphs#c_di_gmp"
  ],
  "rationale": "A bare `induces` edge from a diffusible signal to a community-scale outcome is a placeholder where a mechanism should be. The graph already carries c_di_gmp, but only as a promoter of sessile_state, so it cannot currently express the route most often proposed for this effect. The distinction is not academic: if dispersal runs through the c-di-GMP pool, then strains holding that pool high are intrinsically refractory to the NO-releasing antibiofilm agents now in development -- a resistance mechanism this graph has no way to represent while the edge stays bare.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/biofilm_formation.html#kgscan-aa46cc9b34ab"
 },
 {
  "discussion_id": "kgscan-93e87bc8aba3",
  "prompt": "This record's graph enumerates bsl1 through bsl5, but BSL-5 is not an assigned containment level in any current national framework -- it appears in proposals for hypothetical agents beyond BSL-4. Is the bsl5 node a real classification this record should carry, or a seeded artefact to retract?",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "biosafety level",
  "source_id": "METPO:1001101",
  "source_file": "biosafety_level.yaml",
  "attaches_to": [
   "causal_graphs#bsl5"
  ],
  "rationale": "A containment level that does not exist in regulation is not a value the trait can take, and anything downstream that enumerates levels from this graph -- a risk-assessment form, an ontology mapping, a facility-capability query -- would inherit a level with no requirements attached to it. Note what the resolution is NOT: the node is already labelled a proposal and grounded to METPO:1001106, which the corpus carries as its own seeded record at ecology/biosafety_level_5.yaml, so deleting it here would desynchronise this graph from an upstream-seeded record rather than fix anything. A METPO class is not a citable proposal, so the question stands -- but it is answered by finding the source behind METPO:1001106, and any retraction belongs upstream in METPO, not in this graph.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/biosafety_level.html#kgscan-93e87bc8aba3"
 },
 {
  "discussion_id": "kgscan-066a51aacfb6",
  "prompt": "BSL-2 requires a biosafety cabinet specifically for procedures with aerosol or splash potential, while other work may go on the open bench. Which procedures actually generate an infectious dose at the breathing zone, and does the current procedure list match them?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "biosafety level 2",
  "source_id": "METPO:1001103",
  "source_file": "biosafety_level_2.yaml",
  "attaches_to": [
   "causal_graphs#aerosol_splash_procedure",
   "causal_graphs#biosafety_cabinet"
  ],
  "rationale": "The bench/cabinet boundary is the single control that most BSL-2 work turns on, and it is drawn from procedure lists that long predate quantitative aerosol measurement. A procedure that is on the open bench but does generate respirable particles is an unrecognised exposure; one needlessly in the cabinet costs throughput. Either way the edge into biosafety_cabinet is asserting something measurable that has not been measured.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/biosafety_level_2.html#kgscan-066a51aacfb6"
 },
 {
  "discussion_id": "kgscan-2ee31ba13f9c",
  "prompt": "BSL-3 boundary integrity is verified by pressure-decay testing of the room envelope. Does passing a pressure-decay test predict containment of an airborne agent under real operating conditions, with doors cycling and equipment running?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "biosafety level 3",
  "source_id": "METPO:1001104",
  "source_file": "biosafety_level_3.yaml",
  "attaches_to": [
   "causal_graphs#boundary_integrity_testing",
   "causal_graphs#pressure_decay_testing"
  ],
  "rationale": "The graph routes verification the other way round from the claim it supports: bsl3_trait is `verified by` boundary_integrity_testing, which `utilizes` pressure_decay_testing. So the decay test stands in for containment without any node asserting that containment holds. The test is also performed on a sealed, static room, and the room only matters when it is occupied and in use. If the two diverge, facilities are certified against a condition they never operate in.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/biosafety_level_3.html#kgscan-2ee31ba13f9c"
 },
 {
  "discussion_id": "kgscan-e770cf01677c",
  "prompt": "Every BSL-4 control this record requires assumes terrestrial gravity and somewhere to put contaminated air, water and waste -- suit overpressure, airlocks, chemical showers, specialized waste disposal. Which still contain an agent in a closed-loop habitat that recycles all three?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "biosafety level 4",
  "source_id": "METPO:1001105",
  "source_file": "biosafety_level_4.yaml",
  "attaches_to": [
   "causal_graphs#positive_pressure_suit",
   "causal_graphs#airlock",
   "causal_graphs#decontamination_shower",
   "causal_graphs#specialized_waste_disposal"
  ],
  "rationale": "Sample-return and crewed-habitat missions need containment for agents with no countermeasure, which is exactly what BSL-4 is for. But every control edge runs outward from bsl4_trait to a piece of equipment -- `requires` an airlock, a decontamination shower, specialized waste disposal; `necessitates use of` a positive pressure suit -- so the controls are named as hardware rather than as the physics they rely on, and it is the physics that does or does not transfer. Sedimentation-dependent controls behave differently in microgravity, and a shower and a waste stream that both feed a recycling loop are not disposal. As written the record cannot distinguish a control that survives the move from one that does not, because it never says what any of them do.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/biosafety_level_4.html#kgscan-e770cf01677c"
 },
 {
  "discussion_id": "kgscan-3606bdcc991b",
  "prompt": "Commensalism is defined in this record by a neutral effect on host fitness. Has neutrality ever been measured for these associations, or is it inferred from the absence of visible disease -- and does it hold when the host is stressed, starved, or co-infected?",
  "kind": "KNOWLEDGE_GAP",
  "status": "OPEN",
  "is_gap": "Knowledge gap",
  "source_name": "commensalism",
  "source_id": "traitmech:000042",
  "source_file": "commensalism.yaml",
  "attaches_to": [
   "causal_graphs#neutral_host_fitness"
  ],
  "rationale": "Neutral_host_fitness is the node that makes this trait different from mutualism and parasitism, and it is the one node stated as a definition rather than an observation. If neutrality is only ever the null result of an underpowered comparison in an unstressed host, then commensalism is a measurement category rather than a biological one, and records assigned to it are provisional in a way the corpus does not currently mark.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/commensalism.html#kgscan-3606bdcc991b"
 },
 {
  "discussion_id": "kgscan-a6758e26f5a6",
  "prompt": "Two edges reach genome reduction here: confined habitat through metabolic gene loss, and the trait itself, whose description bundles drift in as `with small Ne`. The nodes that would give drift a mechanism -- transmission bottleneck, limited recombination -- connect to neither. Should they feed the drift edge, and which mechanism dominates?",
  "kind": "CONTROVERSY",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "endosymbiosis",
  "source_id": "traitmech:000045",
  "source_file": "endosymbiosis.yaml",
  "attaches_to": [
   "causal_graphs#reductive_genome_evolution",
   "causal_graphs#transmission_bottleneck",
   "causal_graphs#limited_recombination",
   "causal_graphs#metabolic_gene_loss"
  ],
  "rationale": "The record asserts both mechanisms but at different resolutions, which is what makes them impossible to weigh. Drift arrives bundled into a trait-level edge as a parenthetical -- `with small Ne` inside a description -- while selection is spelled out as a two-step path through metabolic_gene_loss. transmission_bottleneck and limited_recombination attach to each other and to nothing else, so the drift claim has no mechanism under it, and host_symbiont_aa_complementarity -> nutritional_compensation is likewise its own disconnected pair, so compensation is not wired into reduction either. The two predict opposite loss spectra -- drift removes genes roughly regardless of function, compensation removes exactly the genes whose products the host supplies -- so until they are stated at the same resolution the graph cannot say what a newly sequenced symbiont will have lost, which is most of what a reduction model is for.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/endosymbiosis.html#kgscan-a6758e26f5a6"
 },
 {
  "discussion_id": "kgscan-d5aefedf82bb",
  "prompt": "Ectoine and glycine betaine both enable osmotic stress tolerance here, but trehalose is wired instead to environmental stress tolerance -- a node with no outgoing edge. Is that split a real distinction, or does trehalose belong on the osmotic route too?",
  "kind": "KNOWLEDGE_GAP",
  "status": "RESOLVED",
  "is_gap": "Knowledge gap",
  "source_name": "free-living",
  "source_id": "traitmech:000048",
  "source_file": "free_living.yaml",
  "attaches_to": [
   "causal_graphs#osmotic_stress_tolerance",
   "causal_graphs#environmental_stress_tolerance",
   "causal_graphs#ectoine_biosynthesis",
   "causal_graphs#glycine_betaine_system",
   "causal_graphs#trehalose_biosynthesis"
  ],
  "rationale": "Because environmental_stress_tolerance has no outgoing edge, nothing downstream depends on trehalose at all: this record currently predicts the trait's osmotolerance from two systems and leaves the third dangling. Either reading has a consequence. If trehalose does serve osmotic tolerance, a genome carrying only trehalose scores as non-osmotolerant when it is not, which is exactly the inference anything reading habitat range off gene content would make. If the split is real -- trehalose for desiccation and thermal stress rather than osmolarity -- then the dangling node needs its own edge onward to the trait. The second question, whether the two routes that do converge are redundant or condition-partitioned, rides along on the same experiment: their costs differ sharply, since de novo ectoine synthesis is carbon-expensive where betaine uptake is cheap given a precursor.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/free_living.html#kgscan-d5aefedf82bb"
 },
 {
  "discussion_id": "kgscan-4fc1a06fa1e3",
  "prompt": "This record commits to luminal oxygen limitation contributing to the primary fermenter community. Does the reverse arm hold too -- do the fermenters and the epithelium maintain the anoxia -- making this a feedback loop rather than the one-way edge drawn?",
  "kind": "KNOWLEDGE_GAP",
  "status": "RESOLVED",
  "is_gap": "Knowledge gap",
  "source_name": "gut-associated",
  "source_id": "traitmech:000052",
  "source_file": "gut_associated.yaml",
  "attaches_to": [
   "causal_graphs#luminal_oxygen_limitation",
   "causal_graphs#primary_fermenter_community"
  ],
  "rationale": "The existing edge is not wrong so much as half: it says the anoxic lumen permits the fermenters, and stops. If the return arm also holds, the two nodes are a self-reinforcing loop, and losing the fermenters raises luminal oxygen and admits facultative pathogens -- the collapse that follows antibiotic depletion. That is the clinically load-bearing half, and a graph of one-way edges can only carry it if someone draws it.",
  "num_experiments": 1,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "claude",
  "page_url": "../../pages/traits/ecology/gut_associated.html#kgscan-4fc1a06fa1e3"
 },
 {
  "discussion_id": "nitrification-component-go-xref-gap",
  "prompt": "Resolve an exact external ontology class for the complete nitrification process before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "nitrification",
  "source_id": "METPO:1005001",
  "source_file": "nitrification.yaml",
  "attaches_to": [],
  "rationale": "METPO cites GO:0019329 ammonia oxidation and GO:0019332 nitrite oxidation as definition components, but each GO term covers only one half of the full two-step nitrification trait and is not exact enough for TraitRecord xrefs.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/metabolism/nitrification.html#nitrification-component-go-xref-gap"
 },
 {
  "discussion_id": "catalase-negative-assay-parent-gap",
  "prompt": "Resolve a non-assay parent for negative catalase-test phenotypes before narrowing parent_traits below phenotype.",
  "kind": "CURATION_TODO",
  "status": "RESOLVED",
  "is_gap": "Other discussion",
  "source_name": "catalase negative",
  "source_id": "METPO:1007084",
  "source_file": "catalase_negative.yaml",
  "attaches_to": [],
  "rationale": "METPO:1007080 is now represented as the seeded catalase-test assay parent, so this negative assay-outcome phenotype can use its source superclass rather than a temporary direct phenotype parent.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/other/catalase_negative.html#catalase-negative-assay-parent-gap"
 },
 {
  "discussion_id": "indole-test-positive-assay-parent-gap",
  "prompt": "Resolve a non-assay parent for positive indole-test phenotypes before narrowing parent_traits below phenotype.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "indole test positive",
  "source_id": "METPO:1005011",
  "source_file": "indole_test_positive.yaml",
  "attaches_to": [],
  "rationale": "METPO:1005010 is the seeded superclass of METPO:1005011, but METPO:1005010 defines an assay rather than a broader microbial trait class, so this record is temporarily parented directly to METPO:1000059 phenotype.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/other/indole_test_positive.html#indole-test-positive-assay-parent-gap"
 },
 {
  "discussion_id": "non-hemolytic-parent-gap",
  "prompt": "Resolve a neutral parent axis for absence of hemolysis before narrowing parent_traits below phenotype.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "non-hemolytic",
  "source_id": "METPO:1005027",
  "source_file": "non_hemolytic.yaml",
  "attaches_to": [],
  "rationale": "METPO:1005025 is the seeded superclass of METPO:1005027, but METPO:1005025 defines the ability to lyse red blood cells; this absence phenotype is temporarily parented directly to METPO:1000059 phenotype until METPO has a neutral hemolysis axis or another broader parent for hemolysis-test outcomes.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/other/non_hemolytic.html#non-hemolytic-parent-gap"
 },
 {
  "discussion_id": "acid-phosphatase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for acid phosphatase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "acid phosphatase activity",
  "source_id": "traitmech:000142",
  "source_file": "acid_phosphatase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0003993 carries the same acid phosphatase activity label but denotes the enzyme molecular function rather than the organism-level phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/acid_phosphatase_activity.html#acid-phosphatase-activity-xref-gap"
 },
 {
  "discussion_id": "alkaline-phosphatase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for alkaline phosphatase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "alkaline phosphatase activity",
  "source_id": "traitmech:000141",
  "source_file": "alkaline_phosphatase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004035 carries the same alkaline phosphatase activity label but denotes the enzyme molecular function rather than the organism-level phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/alkaline_phosphatase_activity.html#alkaline-phosphatase-activity-xref-gap"
 },
 {
  "discussion_id": "alpha-fucosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for alpha-fucosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "alpha-fucosidase activity",
  "source_id": "traitmech:000152",
  "source_file": "alpha_fucosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004560 carries the alpha-L-fucosidase activity label but denotes the enzyme molecular function rather than the organism-level alpha-fucosidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/alpha_fucosidase_activity.html#alpha-fucosidase-activity-xref-gap"
 },
 {
  "discussion_id": "alpha-galactosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for alpha-galactosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "alpha-galactosidase activity",
  "source_id": "traitmech:000149",
  "source_file": "alpha_galactosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004557 denotes the alpha-galactosidase/melibiase molecular function rather than the organism-level alpha-galactosidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/alpha_galactosidase_activity.html#alpha-galactosidase-activity-xref-gap"
 },
 {
  "discussion_id": "alpha-glucosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for alpha-glucosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "alpha-glucosidase activity",
  "source_id": "traitmech:000145",
  "source_file": "alpha_glucosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0090599 carries the same alpha-glucosidase activity label but denotes the enzyme molecular function rather than the organism-level alpha-glucosidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/alpha_glucosidase_activity.html#alpha-glucosidase-activity-xref-gap"
 },
 {
  "discussion_id": "alpha-mannosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for alpha-mannosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "alpha-mannosidase activity",
  "source_id": "traitmech:000150",
  "source_file": "alpha_mannosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004559 carries the same alpha-mannosidase activity label but denotes the enzyme molecular function rather than the organism-level alpha-mannosidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/alpha_mannosidase_activity.html#alpha-mannosidase-activity-xref-gap"
 },
 {
  "discussion_id": "beta-galactosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for beta-galactosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "beta-galactosidase activity",
  "source_id": "traitmech:000148",
  "source_file": "beta_galactosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004565 carries the same beta-galactosidase activity label but denotes the enzyme molecular function rather than the organism-level beta-galactosidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/beta_galactosidase_activity.html#beta-galactosidase-activity-xref-gap"
 },
 {
  "discussion_id": "beta-glucosidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for beta-glucosidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "beta-glucosidase activity",
  "source_id": "traitmech:000146",
  "source_file": "beta_glucosidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0008422 denotes the beta-D-glucosidase molecular function rather than the organism-level beta-glucosidase production phenotype, so it belongs as a causal-node grounding when a mechanistic graph needs the catalytic activity but not as an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/beta_glucosidase_activity.html#beta-glucosidase-activity-xref-gap"
 },
 {
  "discussion_id": "beta-glucuronidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for beta-glucuronidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "beta-glucuronidase activity",
  "source_id": "traitmech:000151",
  "source_file": "beta_glucuronidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004566 carries the same beta-glucuronidase activity label but denotes the enzyme molecular function rather than the organism-level beta-glucuronidase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/beta_glucuronidase_activity.html#beta-glucuronidase-activity-xref-gap"
 },
 {
  "discussion_id": "caseinase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for caseinase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "caseinase activity",
  "source_id": "traitmech:000137",
  "source_file": "caseinase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0008233 is a generic peptidase-activity class and is too broad for caseinase activity as an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/caseinase_activity.html#caseinase-activity-xref-gap"
 },
 {
  "discussion_id": "cystine-arylamidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for cystine arylamidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "cystine arylamidase activity",
  "source_id": "traitmech:000147",
  "source_file": "cystine_arylamidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004177 covers aminopeptidase activity at molecular-function scope and no live GO class provides an exact residue-specific cystine arylamidase production phenotype at organism-level scope.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/cystine_arylamidase_activity.html#cystine-arylamidase-activity-xref-gap"
 },
 {
  "discussion_id": "dnase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for DNase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "DNase activity",
  "source_id": "traitmech:000138",
  "source_file": "dnase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004536 denotes the DNA nuclease molecular function rather than the organism-level DNase production phenotype, so it is too scope-shifted for an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/dnase_activity.html#dnase-activity-xref-gap"
 },
 {
  "discussion_id": "gelatinase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for gelatinase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "gelatinase activity",
  "source_id": "traitmech:000136",
  "source_file": "gelatinase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0008233 is the generic peptidase-activity class and MICRO:0000649 denotes a gelatinase assay, so both are too broad or assay-level for equivalent TraitRecord xrefs.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/gelatinase_activity.html#gelatinase-activity-xref-gap"
 },
 {
  "discussion_id": "lecithinase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for lecithinase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "lecithinase activity",
  "source_id": "traitmech:000140",
  "source_file": "lecithinase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004629 denotes C-type glycerophospholipase molecular function rather than the organism-level lecithinase production phenotype, so it is too scope-shifted for an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/lecithinase_activity.html#lecithinase-activity-xref-gap"
 },
 {
  "discussion_id": "leucine-arylamidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for leucine arylamidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "leucine arylamidase activity",
  "source_id": "traitmech:000143",
  "source_file": "leucine_arylamidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004177 covers aminopeptidase activity at molecular-function scope and the obsolete GO leucyl aminopeptidase term no longer provides a live exact class for leucine arylamidase production as an organism-level phenotype.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/leucine_arylamidase_activity.html#leucine-arylamidase-activity-xref-gap"
 },
 {
  "discussion_id": "lipase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for lipase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "lipase activity",
  "source_id": "traitmech:000139",
  "source_file": "lipase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0016298 denotes the lipase molecular function rather than the organism-level lipase production phenotype, so it is too scope-shifted for an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/lipase_activity.html#lipase-activity-xref-gap"
 },
 {
  "discussion_id": "lysine-decarboxylase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for lysine decarboxylase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "lysine decarboxylase activity",
  "source_id": "traitmech:000153",
  "source_file": "lysine_decarboxylase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0008923 carries the same lysine decarboxylase activity label but denotes the enzyme molecular function rather than the organism-level lysine decarboxylase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/lysine_decarboxylase_activity.html#lysine-decarboxylase-activity-xref-gap"
 },
 {
  "discussion_id": "ornithine-decarboxylase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for ornithine decarboxylase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "ornithine decarboxylase activity",
  "source_id": "traitmech:000154",
  "source_file": "ornithine_decarboxylase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004586 carries the same ornithine decarboxylase activity label but denotes the enzyme molecular function rather than the organism-level ornithine decarboxylase production phenotype, so it is appropriate as a causal-node grounding rather than an equivalent TraitRecord xref.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/ornithine_decarboxylase_activity.html#ornithine-decarboxylase-activity-xref-gap"
 },
 {
  "discussion_id": "valine-arylamidase-activity-xref-gap",
  "prompt": "Resolve an exact external ontology class for valine arylamidase activity before adding a TraitRecord xref.",
  "kind": "CURATION_TODO",
  "status": "OPEN",
  "is_gap": "Other discussion",
  "source_name": "valine arylamidase activity",
  "source_id": "traitmech:000144",
  "source_file": "valine_arylamidase_activity.yaml",
  "attaches_to": [],
  "rationale": "GO:0004177 covers aminopeptidase activity at molecular-function scope and no live GO class provides an exact residue-specific valine arylamidase production phenotype at organism-level scope.",
  "num_experiments": 0,
  "num_evidence": 0,
  "evidence_refs": [],
  "posed_by": "codex",
  "page_url": "../../pages/traits/physiology/valine_arylamidase_activity.html#valine-arylamidase-activity-xref-gap"
 }
];
window.searchMetrics = {
 "total_discussions": 33,
 "total_knowledge_gaps": 8,
 "total_source_entries": 33,
 "kinds": [
  "CONTROVERSY",
  "CURATION_TODO",
  "KNOWLEDGE_GAP"
 ]
};
window.repoName = "TraitMech";
